Update action.yml

diff --git a/.github/actions/always-step/action.yml b/.github/actions/always-step/action.yml
--- a/.github/actions/always-step/action.yml
+++ b/.github/actions/always-step/action.yml
@@ -7,8 +7,8 @@ runs:
     - name: 'Fail the workflow'
       id: check-step
       run: |
-        echo "WORKFLOW_CONCLUSION=failure" >> $GITHUB_ENV
-        exit 1
+        # echo "WORKFLOW_CONCLUSION=failure" >> $GITHUB_ENV
+        # exit 1
         echo "WORKFLOW_CONCLUSION=completed" >> $GITHUB_ENV
       shell: bash
       
